apiVersion: v1
clusters:
- cluster:
    certificate-authority: /home/victoria/.minikube/ca.crt
    extensions:
    - extension:
        last-update: Thu, 15 May 2025 05:38:23 WAT
        provider: minikube.sigs.k8s.io
        version: v1.35.0
      name: cluster_info
    server: https://127.0.0.1:52017
  name: minikube
contexts:
- context:
    cluster: minikube
    extensions:
    - extension:
        last-update: Thu, 15 May 2025 05:38:23 WAT
        provider: minikube.sigs.k8s.io
        version: v1.35.0
      name: context_info
    namespace: default
    user: minikube
  name: minikube
current-context: minikube
kind: Config
preferences: {}
users:
- name: minikube
  user:
    client-certificate: /home/victoria/.minikube/profiles/minikube/client.crt
    client-key: /home/victoria/.minikube/profiles/minikube/client.key
